name: Build Status


on: [push]

jobs:
  call-python-example:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Local Action Call
        uses: ./example-python/.github/workflows/build.yml